 import { useState, useEffect } from "react";
 import { useLocation, useNavigate, Link } from "react-router-dom";
 import { Button } from "@/components/ui/button";
 import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
 import { Input } from "@/components/ui/input";
 import { Label } from "@/components/ui/label";
 import { Badge } from "@/components/ui/badge";
 import { Separator } from "@/components/ui/separator";
 import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group";
 import {
   Hexagon,
   ArrowLeft,
   CreditCard,
   Smartphone,
   Wallet,
   Banknote,
   Calendar,
   Clock,
   MapPin,
   Star,
   CheckCircle2,
   Loader2,
   Shield,
 } from "lucide-react";
 import { format } from "date-fns";
 import { cn } from "@/lib/utils";
 import { supabase } from "@/integrations/supabase/client";
 import { useToast } from "@/hooks/use-toast";
 import { createNotification } from "@/hooks/useNotifications";
 
 type PaymentMethod = "upi" | "card" | "wallet" | "cod";
 
 interface PaymentState {
   providerId: string;
   date: Date;
   time: string;
   provider: {
     id: number;
     name: string;
     category: string;
     rating: number;
     reviews: number;
     location: string;
     avatar: string;
     basePrice: number;
     visitCharge: number;
   };
 }
 
 const paymentMethods = [
   {
     id: "upi" as PaymentMethod,
     label: "UPI",
     description: "Pay using Google Pay, PhonePe, Paytm",
     icon: Smartphone,
   },
   {
     id: "card" as PaymentMethod,
     label: "Credit / Debit Card",
     description: "Visa, Mastercard, RuPay",
     icon: CreditCard,
   },
   {
     id: "wallet" as PaymentMethod,
     label: "Wallet",
     description: "Paytm, Amazon Pay, Mobikwik",
     icon: Wallet,
   },
   {
     id: "cod" as PaymentMethod,
     label: "Cash on Delivery",
     description: "Pay after service completion",
     icon: Banknote,
   },
 ];
 
 const PaymentPage = () => {
   const location = useLocation();
   const navigate = useNavigate();
   const { toast } = useToast();
   const [paymentMethod, setPaymentMethod] = useState<PaymentMethod>("upi");
   const [upiId, setUpiId] = useState("");
   const [isProcessing, setIsProcessing] = useState(false);
   const [bookingComplete, setBookingComplete] = useState(false);
   const [bookingId, setBookingId] = useState<string | null>(null);
 
   const state = location.state as PaymentState | null;
 
  // Redirect if no booking data
  useEffect(() => {
    if (!state) {
      navigate("/dashboard");
    }
  }, [state, navigate]);
 
   if (!state) {
     return null;
   }
 
   const { provider, date, time } = state;
 
   // Calculate pricing
   const subtotal = provider.basePrice;
   const visitCharge = provider.visitCharge;
   const tax = Math.round((subtotal + visitCharge) * 0.18);
   const total = subtotal + visitCharge + tax;
 
   const handlePayment = async () => {
     setIsProcessing(true);
 
     try {
       // Get current user
       const { data: { user }, error: userError } = await supabase.auth.getUser();
       
       if (userError || !user) {
         toast({
           title: "Authentication required",
           description: "Please log in to complete your booking",
           variant: "destructive",
         });
         navigate("/auth");
         return;
       }
 
        // Create booking in database
        const { data: booking, error: bookingError } = await supabase
          .from("bookings")
          .insert({
            booking_id: "temp", // Will be auto-generated by trigger
            customer_id: user.id,
            provider_id: state.providerId, // Use the actual provider's user_id
            service_category: provider.category,
            scheduled_date: format(new Date(date), "yyyy-MM-dd"),
            scheduled_time: time,
            status: "requested",
            payment_method: paymentMethod,
            payment_status: paymentMethod === "cod" ? "pending" : "paid",
            subtotal: subtotal,
            visit_charge: visitCharge,
            tax: tax,
            total_amount: total,
          })
          .select()
          .single();
 
       if (bookingError) {
         console.error("Booking error:", bookingError);
         throw new Error(bookingError.message);
       }
 
       // Send notification to customer
       await createNotification(
         user.id,
         "Booking Confirmed! 📅",
         `Your ${provider.category} service has been booked for ${format(new Date(date), "MMM d")} at ${time}. Booking ID: ${booking.booking_id}`,
         "booking",
         `/booking/${booking.id}`
       );
 
       // Note: In a real app, we'd also notify the provider here
       // For now, the provider_id is set to user.id (demo mode)
 
       // Set booking complete
       setBookingId(booking.booking_id);
       setBookingComplete(true);
 
       toast({
         title: "Booking Confirmed!",
         description: `Your booking ID is ${booking.booking_id}`,
       });
 
     } catch (error: any) {
       console.error("Payment error:", error);
       toast({
         title: "Booking failed",
         description: error.message || "Something went wrong. Please try again.",
         variant: "destructive",
       });
     } finally {
       setIsProcessing(false);
     }
   };
 
   // Success Screen
   if (bookingComplete && bookingId) {
     return (
       <div className="flex min-h-screen flex-col items-center justify-center bg-background p-4">
         <Card className="w-full max-w-md text-center">
           <CardContent className="pt-8">
             <div className="mx-auto mb-4 flex h-16 w-16 items-center justify-center rounded-full bg-emerald-500/10">
               <CheckCircle2 className="h-10 w-10 text-emerald-500" />
             </div>
             <h1 className="mb-2 text-2xl font-bold text-foreground">Booking Confirmed!</h1>
             <p className="mb-6 text-muted-foreground">
               Your service provider has been notified
             </p>
 
             <div className="mb-6 rounded-lg bg-accent p-4">
               <p className="text-sm text-muted-foreground">Booking ID</p>
               <p className="text-xl font-bold text-primary">{bookingId}</p>
             </div>
 
             <div className="mb-6 space-y-3 text-left">
               <div className="flex items-center gap-3 rounded-lg border border-border p-3">
                 <Calendar className="h-5 w-5 text-muted-foreground" />
                 <div>
                   <p className="text-sm text-muted-foreground">Date</p>
                   <p className="font-medium">{format(new Date(date), "EEEE, MMMM d, yyyy")}</p>
                 </div>
               </div>
               <div className="flex items-center gap-3 rounded-lg border border-border p-3">
                 <Clock className="h-5 w-5 text-muted-foreground" />
                 <div>
                   <p className="text-sm text-muted-foreground">Time</p>
                   <p className="font-medium">{time}</p>
                 </div>
               </div>
               <div className="flex items-center gap-3 rounded-lg border border-border p-3">
                 <Banknote className="h-5 w-5 text-muted-foreground" />
                 <div>
                   <p className="text-sm text-muted-foreground">Total Amount</p>
                   <p className="font-medium">₹{total}</p>
                 </div>
               </div>
             </div>
 
             <Badge variant="secondary" className="mb-6">
               Status: Requested
             </Badge>
 
              <div className="flex flex-col gap-3">
                <Button asChild>
                  <Link to="/dashboard">Go to Dashboard</Link>
                </Button>
                <Button variant="outline" asChild>
                  <Link to="/bookings">View All Bookings</Link>
                </Button>
             </div>
           </CardContent>
         </Card>
       </div>
     );
   }
 
   return (
     <div className="min-h-screen bg-background">
       {/* Header */}
       <header className="sticky top-0 z-50 border-b border-border/50 bg-background/80 backdrop-blur-lg">
         <div className="container mx-auto flex h-16 items-center justify-between px-4">
           <div className="flex items-center gap-4">
             <Button variant="ghost" size="icon" onClick={() => navigate(-1)}>
               <ArrowLeft className="h-5 w-5" />
             </Button>
             <div className="flex items-center gap-2">
               <div className="flex h-9 w-9 items-center justify-center rounded-lg bg-primary">
                 <Hexagon className="h-5 w-5 text-primary-foreground" fill="currentColor" />
               </div>
               <span className="text-xl font-bold text-foreground">
                 Handy<span className="text-primary">Hive</span>
               </span>
             </div>
           </div>
           <h1 className="text-lg font-semibold">Payment</h1>
         </div>
       </header>
 
       <main className="container mx-auto px-4 py-6">
         <div className="grid gap-6 lg:grid-cols-3">
           {/* Payment Methods */}
           <div className="lg:col-span-2 space-y-6">
             <Card>
               <CardHeader>
                 <CardTitle className="flex items-center gap-2">
                   <CreditCard className="h-5 w-5 text-primary" />
                   Select Payment Method
                 </CardTitle>
               </CardHeader>
               <CardContent>
                 <RadioGroup
                   value={paymentMethod}
                   onValueChange={(value) => setPaymentMethod(value as PaymentMethod)}
                   className="space-y-3"
                 >
                   {paymentMethods.map((method) => (
                     <div
                       key={method.id}
                       className={cn(
                         "flex items-center gap-4 rounded-lg border-2 p-4 transition-colors cursor-pointer",
                         paymentMethod === method.id
                           ? "border-primary bg-primary/5"
                           : "border-border hover:border-primary/50"
                       )}
                       onClick={() => setPaymentMethod(method.id)}
                     >
                       <RadioGroupItem value={method.id} id={method.id} />
                       <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-accent">
                         <method.icon className="h-5 w-5 text-foreground" />
                       </div>
                       <div className="flex-1">
                         <Label
                           htmlFor={method.id}
                           className="cursor-pointer font-medium text-foreground"
                         >
                           {method.label}
                         </Label>
                         <p className="text-sm text-muted-foreground">{method.description}</p>
                       </div>
                     </div>
                   ))}
                 </RadioGroup>
 
                 {/* UPI Input */}
                 {paymentMethod === "upi" && (
                   <div className="mt-4 space-y-2">
                     <Label htmlFor="upi">Enter UPI ID</Label>
                     <Input
                       id="upi"
                       placeholder="yourname@upi"
                       value={upiId}
                       onChange={(e) => setUpiId(e.target.value)}
                     />
                   </div>
                 )}
 
                 {/* Card Details */}
                 {paymentMethod === "card" && (
                   <div className="mt-4 space-y-4">
                     <div className="space-y-2">
                       <Label htmlFor="cardNumber">Card Number</Label>
                       <Input id="cardNumber" placeholder="1234 5678 9012 3456" />
                     </div>
                     <div className="grid grid-cols-2 gap-4">
                       <div className="space-y-2">
                         <Label htmlFor="expiry">Expiry Date</Label>
                         <Input id="expiry" placeholder="MM/YY" />
                       </div>
                       <div className="space-y-2">
                         <Label htmlFor="cvv">CVV</Label>
                         <Input id="cvv" placeholder="123" type="password" />
                       </div>
                     </div>
                   </div>
                 )}
 
                 {/* Wallet Selection */}
                 {paymentMethod === "wallet" && (
                   <div className="mt-4 grid grid-cols-3 gap-3">
                     {["Paytm", "Amazon Pay", "Mobikwik"].map((wallet) => (
                       <Button key={wallet} variant="outline" className="h-16">
                         {wallet}
                       </Button>
                     ))}
                   </div>
                 )}
 
                 {/* COD Notice */}
                 {paymentMethod === "cod" && (
                   <div className="mt-4 rounded-lg bg-amber-500/10 p-4 text-amber-700">
                     <p className="text-sm">
                       <strong>Note:</strong> Please keep exact change ready. Payment will be
                       collected after service completion.
                     </p>
                   </div>
                 )}
               </CardContent>
             </Card>
 
             {/* Security Badge */}
             <div className="flex items-center justify-center gap-2 text-sm text-muted-foreground">
               <Shield className="h-4 w-4" />
               <span>Your payment is secured with 256-bit SSL encryption</span>
             </div>
           </div>
 
           {/* Order Summary Sidebar */}
           <div>
             <Card className="sticky top-24">
               <CardHeader>
                 <CardTitle className="text-base">Order Summary</CardTitle>
               </CardHeader>
               <CardContent className="space-y-4">
                 {/* Provider Info */}
                 <div className="flex items-center gap-3">
                   <div className="flex h-12 w-12 items-center justify-center rounded-full bg-primary/10 font-bold text-primary">
                     {provider.avatar}
                   </div>
                   <div>
                     <p className="font-medium">{provider.name}</p>
                     <p className="text-sm text-muted-foreground">{provider.category}</p>
                   </div>
                 </div>
 
                 <Separator />
 
                 {/* Schedule */}
                 <div className="space-y-2 text-sm">
                   <div className="flex items-center gap-2">
                     <Calendar className="h-4 w-4 text-muted-foreground" />
                     <span>{format(new Date(date), "MMM d, yyyy")}</span>
                   </div>
                   <div className="flex items-center gap-2">
                     <Clock className="h-4 w-4 text-muted-foreground" />
                     <span>{time}</span>
                   </div>
                   <div className="flex items-center gap-2">
                     <MapPin className="h-4 w-4 text-muted-foreground" />
                     <span>{provider.location}</span>
                   </div>
                 </div>
 
                 <Separator />
 
                 {/* Price Breakdown */}
                 <div className="space-y-2 text-sm">
                   <div className="flex justify-between">
                     <span className="text-muted-foreground">Service Charge</span>
                     <span>₹{subtotal}</span>
                   </div>
                   <div className="flex justify-between">
                     <span className="text-muted-foreground">Visit Charge</span>
                     <span>₹{visitCharge}</span>
                   </div>
                   <div className="flex justify-between">
                     <span className="text-muted-foreground">GST (18%)</span>
                     <span>₹{tax}</span>
                   </div>
                 </div>
 
                 <Separator />
 
                 <div className="flex items-center justify-between text-lg font-bold">
                   <span>Total</span>
                   <span className="text-primary">₹{total}</span>
                 </div>
 
                 <Button
                   className="w-full"
                   size="lg"
                   onClick={handlePayment}
                   disabled={isProcessing}
                 >
                   {isProcessing ? (
                     <>
                       <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                       Processing...
                     </>
                   ) : (
                     <>
                       {paymentMethod === "cod" ? "Confirm Booking" : `Pay ₹${total}`}
                     </>
                   )}
                 </Button>
               </CardContent>
             </Card>
           </div>
         </div>
       </main>
     </div>
   );
 };
 
 export default PaymentPage;